# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
